/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 게임 서버 입장 티켓 발급
         * @description 게임 서버에 입장하기 위한 일회용 티켓을 발급받습니다.
         *     발급받은 `ticket` 은 Socket.IO 연결 시 `auth.ticket` 으로 사용하며,
         *     `ttl` 초 이내에 반드시 소켓 연결을 완료해야 합니다.
         */
        post: operations["issueTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        IssueTicketRequest: {
            /**
             * @description 사용자 고유 ID
             * @example user-123
             */
            userId: string;
            /**
             * @description 게임 내 표시될 닉네임
             * @example 홍길동
             */
            nickname: string;
            /**
             * @description 플레이어 아바타 키 (예: cat, dog, bear)
             * @example cat
             */
            avatar?: string;
            /**
             * @description 숙련자 여부
             * @example false
             */
            skilled?: boolean;
        };
        IssueTicketResponse: {
            /** @enum {boolean} */
            success: true;
            /**
             * @description 게임 서버 Socket.IO 주소 (예: ws://localhost:8080)
             * @example ws://localhost:8080
             */
            gameServerUrl: string;
            /**
             * @description Socket.IO 연결 시 auth.ticket 으로 사용할 일회용 키
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            ticket: string;
            /**
             * @description 티켓 만료 시간 (초)
             * @example 30
             */
            ttl: number;
        };
        ApiErrorResponse: {
            /** @enum {boolean} */
            success: false;
            /**
             * @description 에러 메시지
             * @example 필수 필드가 누락되었습니다.
             */
            message: string;
            /**
             * @description 에러 코드
             * @example MISSING_FIELDS
             */
            code?: string;
            /**
             * @description 누락된 필드 목록
             * @example [
             *       "userId"
             *     ]
             */
            missingFields?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    issueTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueTicketRequest"];
            };
        };
        responses: {
            /** @description 티켓 발급 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "gameServerUrl": "ws://localhost:8080",
                     *       "ticket": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                     *       "ttl": 30
                     *     }
                     */
                    "application/json": components["schemas"]["IssueTicketResponse"];
                };
            };
            /** @description 요청 파라미터 오류 (필수 필드 누락 등) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "필수 필드가 누락되었습니다.",
                     *       "code": "MISSING_FIELDS",
                     *       "missingFields": [
                     *         "userId",
                     *         "nickname"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description 서버 내부 오류 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": false,
                     *       "message": "서버 오류가 발생했습니다.",
                     *       "code": "INTERNAL_SERVER_ERROR"
                     *     }
                     */
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
