/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description `socket.emit("READY", payload)`
         *     플레이어 준비 상태 변경. 모든 플레이어가 ready=true 되면 게임 자동 시작.
         */
        ReadyEventPayload: {
            /** @description true: 준비 완료, false: 준비 취소 */
            isReady: boolean;
        };
        /**
         * @description `socket.emit("MOVE", payload)`
         *     틱택토 보드에 수를 놓습니다.
         *     ```
         *     0 | 1 | 2
         *     ---------
         *     3 | 4 | 5
         *     ---------
         *     6 | 7 | 8
         *     ```
         */
        MoveEventPayload: {
            /** @description 놓을 위치 인덱스 (0-8) */
            move: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
