/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PlayerData: {
            /** @description 플레이어 소켓 연결 ID */
            connId: string;
            nickname: string;
            isReady: boolean;
            /** @description 아바타 키 (예: cat, dog) */
            avatar?: string;
            skilled?: boolean;
        };
        /**
         * @description `socket.on("CONNECTED", handler)`
         *     소켓 연결 성공 시 발생. 이후 ROOM_ASSIGNED 대기.
         */
        ConnectedEvent: {
            /** @enum {boolean} */
            success: true;
            socketId: string;
            message: string;
        };
        /**
         * @description `socket.on("ROOM_ASSIGNED", handler)`
         *     방이 할당되었을 때 발생.
         */
        RoomAssignedEvent: {
            roomId: string;
        };
        /**
         * @description `socket.on("EXISTING_PLAYERS", handler)`
         *     새로 입장한 플레이어에게만 발송. 방에 이미 있는 플레이어 목록.
         */
        ExistingPlayersEvent: {
            players: components["schemas"]["PlayerData"][];
            roomId: string;
        };
        /**
         * @description `socket.on("PLAYER_JOINED", handler)`
         *     기존 플레이어들에게만 발송. 새 플레이어 입장 알림.
         */
        PlayerJoinedEvent: {
            player: components["schemas"]["PlayerData"];
            roomId: string;
        };
        /**
         * @description `socket.on("PLAYER_READY", handler)`
         *     방 전체 브로드캐스트. 플레이어 준비 상태 변경 알림.
         */
        PlayerReadyEvent: {
            connId: string;
            nickname: string;
            avatar?: string;
            isReady: boolean;
            roomId: string;
        };
        /**
         * @description `socket.on("READY_TIMEOUT_STARTED", handler)`
         *     방 정원이 찼지만 전원 READY가 아닐 때 카운트다운 시작.
         */
        ReadyTimeoutStartedEvent: {
            roomId: string;
            /** @description 타임아웃 밀리초 */
            timeoutMs: number;
        };
        /**
         * @description `socket.on("READY_TIMEOUT_EXPIRED", handler)`
         *     READY 타임아웃 만료 — 미준비 플레이어가 방에서 제거됨.
         */
        ReadyTimeoutExpiredEvent: {
            roomId: string;
            /** @description 타임아웃으로 제거된 플레이어 ID */
            connId: string;
            message: string;
        };
        /**
         * @description `socket.on("READY_TIMEOUT_CANCELED", handler)`
         *     진행 중이던 READY 타임아웃이 중단됨.
         */
        ReadyTimeoutCanceledEvent: {
            roomId: string;
            /** @enum {string} */
            reason: "ROOM_NOT_FULL" | "ALL_READY" | "ROOM_UNAVAILABLE";
        };
        /**
         * @description `socket.on("PLAYING", handler)`
         *     모든 플레이어 ready=true 시 게임 시작. 첫 턴 플레이어 정보 포함.
         */
        PlayingEvent: {
            roomId: string;
            /** @enum {string} */
            status: "PLAYING";
            /** @description 첫 턴을 진행할 플레이어 ID */
            currentTurnPlayerId: string;
            /** @description 게임 참가 플레이어 ID 배열 [player1, player2] */
            players: string[];
        };
        /**
         * @description `socket.on("TURN_TIMEOUT_STARTED", handler)`
         *     현재 턴 플레이어의 착수 제한시간 카운트다운 시작.
         */
        TurnTimeoutStartedEvent: {
            roomId: string;
            timeoutMs: number;
            currentTurnPlayerId: string;
        };
        /**
         * @description `socket.on("MOVE_MADE", handler)`
         *     방 전체 브로드캐스트. 플레이어가 수를 놓았을 때 발생.
         */
        MoveMadeEvent: {
            /** @description 수를 놓은 플레이어의 connId */
            connId: string;
            move: number;
            /** @description 서버 타임아웃에 의해 자동 착수된 경우 true */
            isAuto?: boolean;
        };
        /**
         * @description `socket.on("NEXT_TURN", handler)`
         *     방 전체 브로드캐스트. 다음 턴 플레이어가 정해졌을 때 발생.
         */
        NextTurnEvent: {
            roomId: string;
            /** @description 턴 카운트 (0부터 증가) */
            currentTurn: number;
            nextPlayerId: string;
        };
        /**
         * @description `socket.on("GAME_OVER", handler)`
         *     방 전체 브로드캐스트. 게임 종료 시 발생.
         */
        GameOverEvent: {
            roomId: string;
            /** @enum {string} */
            result: "win" | "draw";
            /** @description 승자 connId (무승부 시 null) */
            winner: string | null;
            /** @description 승자의 플레이어 인덱스 */
            winnerIndex: number;
            /** @description 최종 보드 상태 (각 칸에 플레이어 ID 또는 빈 문자열) */
            board: string[];
        };
        /**
         * @description `socket.on("PLAYER_LEFT", handler)`
         *     같은 방의 다른 플레이어들에게만 발송. 플레이어 퇴장 알림.
         */
        PlayerLeftEvent: {
            connId: string;
            nickname: string;
            avatar?: string;
            roomId: string;
        };
        /**
         * @description `socket.on("LEAVE_SUCCESS", handler)`
         *     나간 본인에게만 발송. 방 퇴장 성공 확인.
         */
        LeaveSuccessEvent: {
            /** @enum {boolean} */
            success: true;
            message: string;
        };
        /**
         * @description `socket.on("ERROR", handler)`
         *     에러 발생 시 해당 소켓에 발송.
         */
        SocketErrorEvent: {
            message: string;
            roomId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
