export const animalList: [string, string, string][] = [
  ["🐶", "강아지", "/assets/animals/Dog Face.png"],
  ["🐱", "고양이", "/assets/animals/Cat Face.png"],
  ["🐭", "생쥐", "/assets/animals/Mouse Face.png"],
  ["🐹", "햄스터", "/assets/animals/Hamster.png"],
  ["🐰", "토끼", "/assets/animals/Rabbit Face.png"],
  ["🦊", "여우", "/assets/animals/Fox.png"],
  ["🐻", "곰", "/assets/animals/Bear.png"],
  ["🦝", "너구리", "/assets/animals/Raccoon.png"],
  ["🐨", "코알라", "/assets/animals/Koala.png"],
  ["🐯", "호랑이", "/assets/animals/Tiger Face.png"],
  ["🦁", "사자", "/assets/animals/Lion.png"],
  ["🐮", "소", "/assets/animals/Cow Face.png"],
  ["🐷", "돼지", "/assets/animals/Pig Face.png"],
  ["🐸", "개구리", "/assets/animals/Frog.png"],
  ["🐵", "원숭이", "/assets/animals/Monkey Face.png"],
  ["🦉", "부엉이", "/assets/animals/Owl.png"],
  ["🐢", "거북이", "/assets/animals/Turtle.png"],
  ["🐬", "돌고래", "/assets/animals/Dolphin.png"],
];

export const adjectives: string[] = [
  "행복한",
  "슬픈",
  "화난",
  "지친",
  "활기찬",
  "조용한",
  "시끄러운",
  "따뜻한",
  "차가운",
  "부드러운",
  "강한",
  "약한",
  "빠른",
  "느린",
  "밝은",
  "어두운",
  "현명한",
  "용감한",
  "겸손한",
  "정직한",
  "친절한",
  "엄격한",
  "귀여운",
  "멋진",
  "신비로운",
  "공정한",
  "냉철한",
  "신중한",
  "논리적인",
  "객관적인",
  "분석적인",
  "통찰력있는",
  "예리한",
  "진지한",
  "사려깊은",
  "정의로운",
  "합리적인",
  "균형잡힌",
  "엄정한",
  "철저한",
];

export function getRandomAdj(): string {
  const randomAdj = Math.floor(Math.random() * adjectives.length);
  return adjectives[randomAdj];
}
